<template>
  <v-flex>
    <v-btn fab dark color="indigo">
        <v-icon  @click="addCol" dark>add</v-icon>
    </v-btn>
    
    <v-data-table
      :headers="headers"
      :items="row"
      class="elevation-1"
      hide-actions
    >
      <template slot="items" slot-scope="props">
        <td>{{ props.item.desc }}</td>
        <td>{{ props.item.cod }}</td>
        <td v-for="v in props.item.values" :key="v.anno">
          <v-text-field v-model.number="v.value" aria-placeholder="0" type="number" @keyup="master(v.anno, props.item.cod)"></v-text-field>
        </td>
        
      </template>
    </v-data-table>
  </v-flex>
  
</template>

<script>
import TdText from './TdText.vue'

export default {
  name: "BilaxForm",
  data() {
    return {
      headers: [
        {
          text: "Descrizione",
          align: "left",
          sortable: false,
          value: "desc",
        },
        {
          text: "Codice",
          align: "left",
          sortable: false,
          value: "cod",
        },
        {
          text: "2019",
          align: "left",
          sortable: false,
          value: "numero",
        }
      ],
      row: [
        { desc: "STATO PATRIMONIALE ATTIVO", cod: "PA", values: [{anno: 2019, value: 0}]},
        { desc: "A) Crediti verso soci per versamenti ancora dovuti", cod: "PA.A", values: [{anno: 2019, value: 0}]},
        { desc: "    Crediti verso soci già richiamati", cod: "PA.A1", values: [{anno: 2019, value: 0}]},
        { desc: "    Crediti verso soci non ancora richiamati", cod: "PA.A2", values: [{anno: 2019, value: 0}]},
        { desc: "B) Immobilizzazioni, con separata indicazione di quelle concesse in locazione finanziaria", cod: "PA.B", values: [{anno: 2019, value: 0}]},
        { desc: "    I. Immateriali", cod: "PA.B1", values: [{anno: 2019, value: 0}]},
        { desc: "        1) Costi di impianto e di ampliamento", cod: "PA.B11", values: [{anno: 2019, value: 0}]},
        { desc: "            Costo storico", cod: "PA.B11a", values: [{anno: 2019, value: 0}]},
        { desc: "            (Fondo ammortamenti)", cod: "PA.B11b", values: [{anno: 2019, value: 0}]},
        { desc: "            (Fondo svalutazioni)", cod: "PA.B11c", values: [{anno: 2019, value: 0}]},
        { desc: "        2) Costi di ricerca, di sviluppo e di pubblicità", cod: "PA.B12", values: [{anno: 2019, value: 0}]},
        { desc: "            Costo storico", cod: "PA.B12a", values: [{anno: 2019, value: 0}]},
        { desc: "            (Fondo ammortamenti)", cod: "PA.B12b", values: [{anno: 2019, value: 0}]},
        { desc: "            (Fondo svalutazioni)", cod: "PA.B12c", values: [{anno: 2019, value: 0}]},
        { desc: "        3) Diritti di brevetto industriale e di utilizzo di opere dell'ingegno", cod: "PA.B13", values: [{anno: 2019, value: 0}]},
        { desc: "            Costo storico", cod: "PA.B13a", values: [{anno: 2019, value: 0}]},
        { desc: "            (Fondo ammortamenti)", cod: "PA.B13b", values: [{anno: 2019, value: 0}]},
        { desc: "            (Fondo svalutazioni)", cod: "PA.B13c", values: [{anno: 2019, value: 0}]},
        { desc: "        4) Concessioni, licenze, marchi e diritti simili", cod: "PA.B14", values: [{anno: 2019, value: 0}]},
        { desc: "            Costo storico", cod: "PA.B14a", values: [{anno: 2019, value: 0}]},
        { desc: "            (Fondo ammortamenti)", cod: "PA.B14b", values: [{anno: 2019, value: 0}]},
        { desc: "            (Fondo svalutazioni)", cod: "PA.B14c", values: [{anno: 2019, value: 0}]},
        { desc: "        Differenza da consolidamento", cod: "PA.B18", values: [{anno: 2019, value: 0}]},
        { desc: "        5) Avviamento", cod: "PA.B15", values: [{anno: 2019, value: 0}]},
        { desc: "            Costo storico", cod: "PA.B15a", values: [{anno: 2019, value: 0}]},
        { desc: "            (Fondo ammortamenti)", cod: "PA.B15b", values: [{anno: 2019, value: 0}]},
        { desc: "            (Fondo svalutazioni)", cod: "PA.B15c", values: [{anno: 2019, value: 0}]},
        { desc: "        6) Immobilizzazioni immateriali in corso e acconti", cod: "PA.B16", values: [{anno: 2019, value: 0}]},
        { desc: "        7) Altre", cod: "PA.B17", values: [{anno: 2019, value: 0}]},
        { desc: "            Costo storico", cod: "PA.B17a", values: [{anno: 2019, value: 0}]},
        { desc: "            (Fondo ammortamenti)", cod: "PA.B17b", values: [{anno: 2019, value: 0}]},
        { desc: "            (Fondo svalutazioni)", cod: "PA.B17c", values: [{anno: 2019, value: 0}]},
        { desc: "    II. Materiali", cod: "PA.B2", values: [{anno: 2019, value: 0}]},
        { desc: "        1) Terreni e fabbricati", cod: "PA.B21", values: [{anno: 2019, value: 0}]},
        { desc: "            Costo storico", cod: "PA.B21a", values: [{anno: 2019, value: 0}]},
        { desc: "            (Fondo ammortamenti)", cod: "PA.B21b", values: [{anno: 2019, value: 0}]},
        { desc: "            (Fondo svalutazioni)", cod: "PA.B21c", values: [{anno: 2019, value: 0}]},
        { desc: "        2) Impianti e macchinario", cod: "PA.B22", values: [{anno: 2019, value: 0}]},
        { desc: "            Costo storico", cod: "PA.B22a", values: [{anno: 2019, value: 0}]},
        { desc: "            (Fondo ammortamenti)", cod: "PA.B22b", values: [{anno: 2019, value: 0}]},
        { desc: "            (Fondo svalutazioni)", cod: "PA.B22c", values: [{anno: 2019, value: 0}]},
        { desc: "        3) Attrezzature industriali e commerciali", cod: "PA.B23", values: [{anno: 2019, value: 0}]},
        { desc: "            Costo storico", cod: "PA.B23a", values: [{anno: 2019, value: 0}]},
        { desc: "            (Fondo ammortamenti)", cod: "PA.B23b", values: [{anno: 2019, value: 0}]},
        { desc: "            (Fondo svalutazioni)", cod: "PA.B23c", values: [{anno: 2019, value: 0}]},
        { desc: "        4) Altri beni", cod: "PA.B24", values: [{anno: 2019, value: 0}]},
        { desc: "            Costo storico", cod: "PA.B24a", values: [{anno: 2019, value: 0}]},
        { desc: "            (Fondo ammortamenti)", cod: "PA.B24b", values: [{anno: 2019, value: 0}]},
        { desc: "            (Fondo svalutazioni)", cod: "PA.B24c", values: [{anno: 2019, value: 0}]},
        { desc: "        5) Immobilizzazioni in corso e acconti", cod: "PA.B25", values: [{anno: 2019, value: 0}]},
        { desc: "        6) Concesse in Locazione Finanziaria", cod: "PA.B26", values: [{anno: 2019, value: 0}]},
        { desc: "            Costo storico", cod: "PA.B26a", values: [{anno: 2019, value: 0}]},
        { desc: "            (Fondo ammortamenti)", cod: "PA.B26b", values: [{anno: 2019, value: 0}]},
        { desc: "            (Fondo svalutazioni)", cod: "PA.B26c", values: [{anno: 2019, value: 0}]},
        { desc: "    III. Finanziarie", cod: "PA.B3", values: [{anno: 2019, value: 0}]},
        { desc: "        1) Partecipazioni in:", cod: "PA.B31", values: [{anno: 2019, value: 0}]},
        { desc: "            a) imprese controllate", cod: "PA.B31a", values: [{anno: 2019, value: 0}]},
        { desc: "            b) imprese collegate", cod: "PA.B31b", values: [{anno: 2019, value: 0}]},
        { desc: "            c) imprese controllanti", cod: "PA.B31c", values: [{anno: 2019, value: 0}]},
        { desc: "            d) altre imprese", cod: "PA.B31d", values: [{anno: 2019, value: 0}]},
        { desc: "        2) Crediti", cod: "PA.B32", values: [{anno: 2019, value: 0}]},
        { desc: "            a) verso imprese controllate", cod: "PA.B32a", values: [{anno: 2019, value: 0}]},
        { desc: "                - entro 12 mesi", cod: "PA.B32a1", values: [{anno: 2019, value: 0}]},
        { desc: "                - oltre 12 mesi", cod: "PA.B32a2", values: [{anno: 2019, value: 0}]},
        { desc: "            b) verso imprese collegate", cod: "PA.B32b", values: [{anno: 2019, value: 0}]},
        { desc: "                - entro 12 mesi", cod: "PA.B32b1", values: [{anno: 2019, value: 0}]},
        { desc: "                - oltre 12 mesi", cod: "PA.B32b2", values: [{anno: 2019, value: 0}]},
        { desc: "            c) verso imprese controllanti", cod: "PA.B32c", values: [{anno: 2019, value: 0}]},
        { desc: "                - entro 12 mesi", cod: "PA.B32c1", values: [{anno: 2019, value: 0}]},
        { desc: "                - oltre 12 mesi", cod: "PA.B32c2", values: [{anno: 2019, value: 0}]},
        { desc: "            d) verso altri", cod: "PA.B32d", values: [{anno: 2019, value: 0}]},
        { desc: "                - entro 12 mesi", cod: "PA.B32d1", values: [{anno: 2019, value: 0}]},
        { desc: "                - oltre 12 mesi", cod: "PA.B32d2", values: [{anno: 2019, value: 0}]},
        { desc: "        3) Altri titoli", cod: "PA.B33", values: [{anno: 2019, value: 0}]},
        { desc: "        4) Azioni proprie", cod: "PA.B34", values: [{anno: 2019, value: 0}]},
        { desc: "            Valore nominale complessivo", cod: "PA.B34a", values: [{anno: 2019, value: 0}]},
        { desc: "            Differenza dal valore nominale", cod: "PA.B34b", values: [{anno: 2019, value: 0}]},
        { desc: "C) Attivo circolante", cod: "PA.C", values: [{anno: 2019, value: 0}]},
        { desc: "    I. Rimanenze", cod: "PA.C1", values: [{anno: 2019, value: 0}]},
        { desc: "        1) Materie prime, sussidiarie e di consumo", cod: "PA.C11", values: [{anno: 2019, value: 0}]},
        { desc: "        2) Prodotti in corso di lavorazione e semilavorati", cod: "PA.C12", values: [{anno: 2019, value: 0}]},
        { desc: "        3) Lavori in corso su ordinazione", cod: "PA.C13", values: [{anno: 2019, value: 0}]},
        { desc: "        4) Prodotti finiti e merci", cod: "PA.C14", values: [{anno: 2019, value: 0}]},
        { desc: "        5) Acconti", cod: "PA.C15", values: [{anno: 2019, value: 0}]},
        { desc: "    II. Crediti", cod: "PA.C2", values: [{anno: 2019, value: 0}]},
        { desc: "        1) verso clienti", cod: "PA.C21", values: [{anno: 2019, value: 0}]},
        { desc: "                - entro 12 mesi", cod: "PA.C21a", values: [{anno: 2019, value: 0}]},
        { desc: "                - oltre 12 mesi", cod: "PA.C21b", values: [{anno: 2019, value: 0}]},
        { desc: "        2) verso imprese controllate", cod: "PA.C22", values: [{anno: 2019, value: 0}]},
        { desc: "                - entro 12 mesi", cod: "PA.C22a", values: [{anno: 2019, value: 0}]},
        { desc: "                - oltre 12 mesi", cod: "PA.C22b", values: [{anno: 2019, value: 0}]},
        { desc: "           - entro 12 mesi", cod: "PA.C23a", values: [{anno: 2019, value: 0}]},
        { desc: "           - oltre 12 mesi", cod: "PA.C23b", values: [{anno: 2019, value: 0}]},
        { desc: "       4) verso controllanti", cod: "PA.C24", values: [{anno: 2019, value: 0}]},
        { desc: "           - entro 12 mesi", cod: "PA.C24a", values: [{anno: 2019, value: 0}]},
        { desc: "           - oltre 12 mesi", cod: "PA.C24b", values: [{anno: 2019, value: 0}]},
        { desc: "       4-bis) crediti tributari", cod: "PA.C2B", values: [{anno: 2019, value: 0}]},
        { desc: "           - entro 12 mesi", cod: "PA.C2Ba", values: [{anno: 2019, value: 0}]},
        { desc: "           - oltre 12 mesi", cod: "PA.C2Bb", values: [{anno: 2019, value: 0}]},
        { desc: "       4-ter) Imposte anticipate", cod: "PA.C2T", values: [{anno: 2019, value: 0}]},
        { desc: "           - entro 12 mesi", cod: "PA.C2Ta", values: [{anno: 2019, value: 0}]},
        { desc: "           - oltre 12 mesi", cod: "PA.C2Tb", values: [{anno: 2019, value: 0}]},
        { desc: "       5) verso altri", cod: "PA.C25", values: [{anno: 2019, value: 0}]},
        { desc: "           - entro 12 mesi", cod: "PA.C25a", values: [{anno: 2019, value: 0}]},
        { desc: "           - oltre 12 mesi", cod: "PA.C25b", values: [{anno: 2019, value: 0}]},
        { desc: "   III. Attività finanziarie che non costituiscono immobilizzazioni", cod: "PA.C3", values: [{anno: 2019, value: 0}]},
        { desc: "       1) Partecipazioni in imprese controllate", cod: "PA.C31", values: [{anno: 2019, value: 0}]},
        { desc: "       2) Partecipazioni in imprese collegate", cod: "PA.C32", values: [{anno: 2019, value: 0}]},
        { desc: "       3) Partecipazioni in imprese controllanti", cod: "PA.C33", values: [{anno: 2019, value: 0}]},
        { desc: "       4) Altre partecipazioni", cod: "PA.C34", values: [{anno: 2019, value: 0}]},
        { desc: "       5) Azioni proprie", cod: "PA.C35", values: [{anno: 2019, value: 0}]},
        { desc: "           Valore nominale complessivo", cod: "PA.C35a", values: [{anno: 2019, value: 0}]},
        { desc: "           Differenza dal valore nominale", cod: "PA.C35b", values: [{anno: 2019, value: 0}]},
        { desc: "       6) Altri titoli", cod: "PA.C36", values: [{anno: 2019, value: 0}]},
        { desc: "   IV. Disponibilità liquide", cod: "PA.C4", values: [{anno: 2019, value: 0}]},
        { desc: "       1) Depositi bancari e postali", cod: "PA.C41", values: [{anno: 2019, value: 0}]},
        { desc: "       2) Assegni", cod: "PA.C42", values: [{anno: 2019, value: 0}]},
        { desc: "       3) Denaro e valori in cassa", cod: "PA.C43", values: [{anno: 2019, value: 0}]},
        { desc: "D) Ratei e risconti attivi", cod: "PA.D", values: [{anno: 2019, value: 0}]},
        { desc: "   Disaggio su prestiti", cod: "PA.D1", values: [{anno: 2019, value: 0}]},
        { desc: "   Vari", cod: "PA.D2", values: [{anno: 2019, value: 0}]},
        { desc: "STATO PATRIMONIALE PASSIVO", cod: "PP", values: [{anno: 2019, value: 0}]},
        { desc: "A) Patrimonio netto", cod: "PP.A", values: [{anno: 2019, value: 0}]},
        { desc: "   I. Capitale", cod: "PP.A1", values: [{anno: 2019, value: 0}]},
        { desc: "   II. Riserva da sovrapprezzo delle azioni", cod: "PP.A2", values: [{anno: 2019, value: 0}]},
        { desc: "   III. Riserva di rivalutazione", cod: "PP.A3", values: [{anno: 2019, value: 0}]},
        { desc: "   IV. Riserva legale", cod: "PP.A4", values: [{anno: 2019, value: 0}]},
        { desc: "   V. Riserve statutarie", cod: "PP.A6", values: [{anno: 2019, value: 0}]},
        { desc: "   VI. Riserva per azioni proprie in portafoglio", cod: "PP.A5", values: [{anno: 2019, value: 0}]},
        { desc: "   VII. Altre riserve, distintamente indicate:", cod: "PP.A7", values: [{anno: 2019, value: 0}]},
        { desc: "       Riserva straordinaria o facoltativa", cod: "PP.A7a", values: [{anno: 2019, value: 0}]},
        { desc: "       Riserva per acquisto azioni proprie", cod: "PP.A7n", values: [{anno: 2019, value: 0}]},
        { desc: "       Riserva da deroghe ex art. 2423 Cod.Civ.", cod: "PP.A7o", values: [{anno: 2019, value: 0}]},
        { desc: "       Riserva azioni o quote della società controllante", cod: "PP.A7p", values: [{anno: 2019, value: 0}]},
        { desc: "       Riserva non distribuibile da rivalutazione delle partecipazioni", cod: "PP.A7q", values: [{anno: 2019, value: 0}]},
        { desc: "       Versamenti in conto aumento di capitale", cod: "PP.A7r", values: [{anno: 2019, value: 0}]},
        { desc: "       Versamenti in conto futuro aumento di capitale", cod: "PP.A7s", values: [{anno: 2019, value: 0}]},
        { desc: "       - Versamenti in conto capitale", cod: "PP.A7b", values: [{anno: 2019, value: 0}]},
        { desc: "       Versamenti a copertura perdite", cod: "PP.A7t", values: [{anno: 2019, value: 0}]},
        { desc: "       Riserva da riduzione capitale sociale", cod: "PP.A7u", values: [{anno: 2019, value: 0}]},
        { desc: "       Riserva avanzo di fusione", cod: "PP.A7v", values: [{anno: 2019, value: 0}]},
        { desc: "       Riserva per utili su cambi", cod: "PP.A7w", values: [{anno: 2019, value: 0}]},
        { desc: "       Varie altre riserve", cod: "PP.A7j", values: [{anno: 2019, value: 0}]},
        { desc: "           varie altre riserve", cod: "PP.A7j1", values: [{anno: 2019, value: 0}]},
        { desc: "           - da arrotondamento automatico in Euro (2 decimali)", cod: "PP=A7j2", values: [{anno: 2019, value: 0}]},
        { desc: "       - Riserva di conversione da consolidamento estero", cod: "PP.A7l", values: [{anno: 2019, value: 0}]},
        { desc: "       - Riserva di consolidamento", cod: "PP.A7m", values: [{anno: 2019, value: 0}]},
        { desc: "   VIII. Utili (perdite) portati a nuovo", cod: "PP.A8", values: [{anno: 2019, value: 0}]},
        { desc: "   Utile (Perdita) Residua", cod: "PP.A9", values: [{anno: 2019, value: 0}]},
        { desc: "       Utile (perdita) dell'esercizio", cod: "PP=A9a", values: [{anno: 2019, value: 0}]},
        { desc: "       Copertura Parziale Perdita d'Esercizio", cod: "PP.A9b", values: [{anno: 2019, value: 0}]},
        { desc: "   Patrimonio di Terzi", cod: "PP.AA", values: [{anno: 2019, value: 0}]},
        { desc: "       Capitale e riserve di terzi", cod: "PP.AA1", values: [{anno: 2019, value: 0}]},
        { desc: "       Utile (perdita) dell'esercizio di pertinenza di terzi", cod: "PP=AA2", values: [{anno: 2019, value: 0}]},
        { desc: "B) Fondi per rischi e oneri", cod: "PP.B", values: [{anno: 2019, value: 0}]},
        { desc: "   1) Fondo per trattamento di quiescenza e obblighi simili", cod: "PP.B1", values: [{anno: 2019, value: 0}]},
        { desc: "   2) Fondo per imposte, anche differite", cod: "PP.B2", values: [{anno: 2019, value: 0}]},
        { desc: "   di consolidamento per rischi e oneri futuri", cod: "PP.B4", values: [{anno: 2019, value: 0}]},
        { desc: "   3) Altri fondi", cod: "PP.B3", values: [{anno: 2019, value: 0}]},
        { desc: "C) Trattamento fine rapporto di lavoro subordinato", cod: "PP.C", values: [{anno: 2019, value: 0}]},
        { desc: "D) Debiti", cod: "PP.D", values: [{anno: 2019, value: 0}]},
        { desc: "   1) Obbligazioni non convertibili", cod: "PP.D1", values: [{anno: 2019, value: 0}]},
        { desc: "       - entro 12 mesi", cod: "PP.D1a", values: [{anno: 2019, value: 0}]},
        { desc: "       - oltre 12 mesi", cod: "PP.D1b", values: [{anno: 2019, value: 0}]},
        { desc: "   2) Obbligazioni convertibili", cod: "PP.D2", values: [{anno: 2019, value: 0}]},
        { desc: "       - entro 12 mesi", cod: "PP.D2a", values: [{anno: 2019, value: 0}]},
        { desc: "       - oltre 12 mesi", cod: "PP.D2b", values: [{anno: 2019, value: 0}]},
        { desc: "   3) Debiti verso soci per finanziamenti", cod: "PP.DF", values: [{anno: 2019, value: 0}]},
        { desc: "       - entro 12 mesi", cod: "PP.DFa", values: [{anno: 2019, value: 0}]},
        { desc: "       - oltre 12 mesi", cod: "PP.DFb", values: [{anno: 2019, value: 0}]},
        { desc: "   4) Debiti verso banche", cod: "PP.D3", values: [{anno: 2019, value: 0}]},
        { desc: "       - entro 12 mesi", cod: "PP.D3a", values: [{anno: 2019, value: 0}]},
        { desc: "       - oltre 12 mesi", cod: "PP.D3b", values: [{anno: 2019, value: 0}]},
        { desc: "   5) Debiti verso altri finanziatori", cod: "PP.D4", values: [{anno: 2019, value: 0}]},
        { desc: "       - entro 12 mesi", cod: "PP.D4a", values: [{anno: 2019, value: 0}]},
        { desc: "       - oltre 12 mesi", cod: "PP.D4b", values: [{anno: 2019, value: 0}]},
        { desc: "   6) Acconti", cod: "PP.D5", values: [{anno: 2019, value: 0}]},
        { desc: "       - entro 12 mesi", cod: "PP.D5a", values: [{anno: 2019, value: 0}]},
        { desc: "       - oltre 12 mesi", cod: "PP.D5b", values: [{anno: 2019, value: 0}]},
        { desc: "   7) Debiti verso fornitori", cod: "PP.D6", values: [{anno: 2019, value: 0}]},
        { desc: "       - entro 12 mesi", cod: "PP.D6a", values: [{anno: 2019, value: 0}]},
        { desc: "       - oltre 12 mesi", cod: "PP.D6b", values: [{anno: 2019, value: 0}]},
        { desc: "   8) Debiti rappresentati da titoli di credito", cod: "PP.D7", values: [{anno: 2019, value: 0}]},
        { desc: "       - entro 12 mesi", cod: "PP.D7a", values: [{anno: 2019, value: 0}]},
        { desc: "       - oltre 12 mesi", cod: "PP.D7b", values: [{anno: 2019, value: 0}]},
        { desc: "   9)Debiti verso imprese controllate", cod: "PP.D8", values: [{anno: 2019, value: 0}]},
        { desc: "   - entro 12 mesi", cod: "PP.D8a", values: [{anno: 2019, value: 0}]},
        { desc: "   - oltre 12 mesi", cod: "PP.D8b", values: [{anno: 2019, value: 0}]},
        { desc: "   10)Debiti verso imprese collegate", cod: "PP.D9", values: [{anno: 2019, value: 0}]},
        { desc: "   - entro 12 mesi", cod: "PP.D9a", values: [{anno: 2019, value: 0}]},
        { desc: "   - oltre 12 mesi", cod: "PP.D9b", values: [{anno: 2019, value: 0}]},
        { desc: "   11)Debiti verso controllanti", cod: "PP.DA", values: [{anno: 2019, value: 0}]},
        { desc: "   - entro 12 mesi", cod: "PP.DAa", values: [{anno: 2019, value: 0}]},
        { desc: "   - oltre 12 mesi", cod: "PP.DAb", values: [{anno: 2019, value: 0}]},
        { desc: "   12)Debiti tributari", cod: "PP.DB", values: [{anno: 2019, value: 0}]},
        { desc: "   - entro 12 mesi", cod: "PP.DBa", values: [{anno: 2019, value: 0}]},
        { desc: "   - oltre 12 mesi", cod: "PP.DBb", values: [{anno: 2019, value: 0}]},
        { desc: "   13)Debiti verso istituti di previdenza e sicurezza sociale", cod: "PP.DC", values: [{anno: 2019, value: 0}]},
        { desc: "   - entro 12 mesi", cod: "PP.DCa", values: [{anno: 2019, value: 0}]},
        { desc: "   - oltre 12 mesi", cod: "PP.DCb", values: [{anno: 2019, value: 0}]},
        { desc: "   14) Altri debiti", cod: "PP.DD", values: [{anno: 2019, value: 0}]},
        { desc: "   - entro 12 mesi", cod: "PP.DDa", values: [{anno: 2019, value: 0}]},
        { desc: "   - oltre 12 mesi", cod: "PP.DDb", values: [{anno: 2019, value: 0}]},
        { desc: "E) Ratei e risconti ", cod: "PP.E", values: [{anno: 2019, value: 0}]},
        { desc: "   -aggio su prestiti", cod: "PP.E1", values: [{anno: 2019, value: 0}]},
        { desc: "   -vari", cod: "PP.E2", values: [{anno: 2019, value: 0}]},
        { desc: "CONTI D’ORDINE", cod: "PO", values: [{anno: 2019, value: 0}]},
        { desc: "Rischi assunti dall’impresa", cod: "PO.A", values: [{anno: 2019, value: 0}]},
        { desc: "	Fideiussioni", cod: "PO.A1", values: [{anno: 2019, value: 0}]},
        { desc: "	a imprese controllate", cod: "PO.A1a", values: [{anno: 2019, value: 0}]},
        { desc: "	a imprese collegate", cod: "PO.A1b", values: [{anno: 2019, value: 0}]},
        { desc: "	a imprese controllanti", cod: "PO.A1c", values: [{anno: 2019, value: 0}]},
        { desc: "	a imprese controllate da controllanti", cod: "PO.A1d", values: [{anno: 2019, value: 0}]},
        { desc: "	ad altre imprese", cod: "PO.A1e", values: [{anno: 2019, value: 0}]},
        { desc: "	Avalli", cod: "PO.A2", values: [{anno: 2019, value: 0}]},
        { desc: "	a imprese controllate", cod: "PO.A2a", values: [{anno: 2019, value: 0}]},
        { desc: "	a imprese collegate", cod: "PO.A2b", values: [{anno: 2019, value: 0}]},
        { desc: "	a imprese controllanti", cod: "PO.A2c", values: [{anno: 2019, value: 0}]},
        { desc: "	a imprese controllate da controllanti", cod: "PO.A2d", values: [{anno: 2019, value: 0}]},
        { desc: "	ad altre imprese", cod: "PO.A2e", values: [{anno: 2019, value: 0}]},
        { desc: "	Altre garanzie personali", cod: "PO.A3", values: [{anno: 2019, value: 0}]},
        { desc: "	a imprese controllate", cod: "PO.A3a", values: [{anno: 2019, value: 0}]},
        { desc: "	a imprese collegate", cod: "PO.A3b", values: [{anno: 2019, value: 0}]},
        { desc: "	a imprese controllanti", cod: "PO.A3c", values: [{anno: 2019, value: 0}]},
        { desc: "	a imprese controllate da controllanti", cod: "PO.A3d", values: [{anno: 2019, value: 0}]},
        { desc: "	ad altre imprese", cod: "PO.A3e", values: [{anno: 2019, value: 0}]},
        { desc: "	Garanzie Reali", cod: "PO.A4", values: [{anno: 2019, value: 0}]},
        { desc: "	a imprese controllate", cod: "PO.A4a", values: [{anno: 2019, value: 0}]},
        { desc: "	a imprese collegate", cod: "PO.A4b", values: [{anno: 2019, value: 0}]},
        { desc: "	a imprese controllanti", cod: "PO.A4c", values: [{anno: 2019, value: 0}]},
        { desc: "	a imprese controllate da controllanti", cod: "PO.A4d", values: [{anno: 2019, value: 0}]},
        { desc: "	ad altre imprese", cod: "PO.A4e", values: [{anno: 2019, value: 0}]},
        { desc: "	Altri Rischi", cod: "PO.A5", values: [{anno: 2019, value: 0}]},
        { desc: "	crediti ceduti pro solvendo", cod: "PO.A5a", values: [{anno: 2019, value: 0}]},
        { desc: "	altri", cod: "PO.A5b", values: [{anno: 2019, value: 0}]},
        { desc: "Impegni Assunti dall’impresa", cod: "PO.B", values: [{anno: 2019, value: 0}]},
        { desc: "Beni di terzi presso l’impresa", cod: "PO.C", values: [{anno: 2019, value: 0}]},
        { desc: "	merci in conto lavorazione", cod: "PO.C1", values: [{anno: 2019, value: 0}]},
        { desc: "	beni presso l’impresa a titolo di deposito o comodato", cod: "PO.C2", values: [{anno: 2019, value: 0}]},
        { desc: "	beni presso l’impresa in pegno o cauzione", cod: "PO.C3", values: [{anno: 2019, value: 0}]},
        { desc: "	altro", cod: "PO.C4", values: [{anno: 2019, value: 0}]},
        { desc: "Altri conti d’ordine", cod: "PO.L", values: [{anno: 2019, value: 0}]},
        { desc: "CONTO ECONOMICO", cod: "E", values: [{anno: 2019, value: 0}]},
        { desc: "A) Valore della produzione", cod: "E.A", values: [{anno: 2019, value: 0}]},
        { desc: "	1) Ricavi delle vendite e delle prestazioni", cod: "E.A1", values: [{anno: 2019, value: 0}]},
        { desc: "	2)Variazione rimanenze prodotti in corso di lavor., semilavorati e finiti", cod: "E.A2", values: [{anno: 2019, value: 0}]},
        { desc: "	3) Ricavi delle vendite e delle prestazioni", cod: "E.A1", values: [{anno: 2019, value: 0}]},
        { desc: "	4) Incrementi di Immobilizzazioni per lavori interni", cod: "E.A4", values: [{anno: 2019, value: 0}]},
        { desc: "	5) Altri ricavi e proventi", cod: "E.A5", values: [{anno: 2019, value: 0}]},
        { desc: "	   - Vari", cod: "E.A51", values: [{anno: 2019, value: 0}]},
        { desc: "	   - Contributi in conto esercizio", cod: "E.A52", values: [{anno: 2019, value: 0}]},
        { desc: "B) Costi della produzione", cod: "E.B", values: [{anno: 2019, value: 0}]},
        { desc: "	6) Acquisti materie prime,sussidiarie, di consumo e di merci", cod: "E.B1", values: [{anno: 2019, value: 0}]},
        { desc: "MARGINE LORDO", cod: "ML", values: [{anno: 2019, value: 0}]},
        { desc: "	7) Spese per prestazioni di servizi", cod: "E.B2", values: [{anno: 2019, value: 0}]},
        { desc: "	8) Spese per godimento di beni di terzi", cod: "E.B3", values: [{anno: 2019, value: 0}]},
        { desc: "	9) Costi del personale", cod: "E.B4", values: [{anno: 2019, value: 0}]},
        { desc: "	 	a) Salari e stipendi", cod: "E.B41", values: [{anno: 2019, value: 0}]},
        { desc: "	 	b) Oneri sociali", cod: "E.B42", values: [{anno: 2019, value: 0}]},
        { desc: "	 	c) Trattamento Fine Rapporto", cod: "E.B43", values: [{anno: 2019, value: 0}]},
        { desc: "	 	d) Trattamento di quiescenza e simili", cod: "E.B44", values: [{anno: 2019, value: 0}]},
        { desc: "	 	e) Altri costi", cod: "E.B45", values: [{anno: 2019, value: 0}]},
        { desc: "EBITDA (MOL)", cod: "EBITDA", values: [{anno: 2019, value: 0}]},
        { desc: "	10) Ammortamenti e svalutazioni", cod: "E.B5", values: [{anno: 2019, value: 0}]},
        { desc: "	 	a) Ammortamento delle immobilizzazioni immateriali", cod: "E.B51", values: [{anno: 2019, value: 0}]},
        { desc: "	 	b) Ammortamento delle immobilizzazioni materiali", cod: "E.B52", values: [{anno: 2019, value: 0}]},
        { desc: "	 	c) Altre svalutazioni delle immobilizzazioni", cod: "E.B53", values: [{anno: 2019, value: 0}]},
        { desc: "	 	d) Svalutazione cred. del circol. e delle disponibilità liquide", cod: "E.B54", values: [{anno: 2019, value: 0}]},
        { desc: "	11) Variazioni rimanenze materie prime, sussid., di consume e merci", cod: "E.B6", values: [{anno: 2019, value: 0}]},
        { desc: "	12) Accantonamenti per rischi", cod: "E.B7", values: [{anno: 2019, value: 0}]},
        { desc: "	13) Altri accantonamenti", cod: "E.B8", values: [{anno: 2019, value: 0}]},
        { desc: "	14) Oneri diversi di gestione", cod: "E.B9", values: [{anno: 2019, value: 0}]},
        { desc: "RISULTATO OPERATIVO EBIT", cod: "E=B", values: [{anno: 2019, value: 0}]},
        { desc: "	C) Proventi e oneri finanziari", cod: "E.C", values: [{anno: 2019, value: 0}]},
        { desc: "	15) Proventi e partecipazioni", cod: "E.C1", values: [{anno: 2019, value: 0}]},
        { desc: "		- Imprese controllate", cod: "E.C11", values: [{anno: 2019, value: 0}]},
        { desc: "		- Imprese collegate", cod: "E.C12", values: [{anno: 2019, value: 0}]},
        { desc: "		- Altri", cod: "E.C13", values: [{anno: 2019, value: 0}]},
        { desc: "	16) Altri proventi finanziari", cod: "E.C2", values: [{anno: 2019, value: 0}]},
        { desc: "	  a) da crediti iscritti nelle immobilizzazioni", cod: "E.C21", values: [{anno: 2019, value: 0}]},
        { desc: "            - da imprese controllate", cod: "E.C211", values: [{anno: 2019, value: 0}]},
        { desc: "            - da imprese collegate", cod: "E.C212", values: [{anno: 2019, value: 0}]},
        { desc: "            - da controllanti", cod: "E.C213", values: [{anno: 2019, value: 0}]},
        { desc: "            - altri", cod: "E.C215", values: [{anno: 2019, value: 0}]},
        { desc: "        b) da titoli iscritti nelle immobilizzazioni", cod: "E.C22", values: [{anno: 2019, value: 0}]},
        { desc: "        c) da titoli inscritti nell'attivo circolante", cod: "E.C23", values: [{anno: 2019, value: 0}]},
        { desc: "        d) proventi finanziari diversi dai precedenti:", cod: "E.C24", values: [{anno: 2019, value: 0}]},
        { desc: "            - da imprese controllate", cod: "E.C241", values: [{anno: 2019, value: 0}]},
        { desc: "            - da imprese collegate", cod: "E.C245", values: [{anno: 2019, value: 0}]},
        { desc: "            - da imprese controllanti", cod: "E.C242", values: [{anno: 2019, value: 0}]},
        { desc: "            - altri proventi finanziari", cod: "E.C244", values: [{anno: 2019, value: 0}]},
        { desc: "    17) Interessi e altri oneri finanziari:", cod: "E.C3", values: [{anno: 2019, value: 0}]},
        { desc: "        - da imprese controllate", cod: "E.C31", values: [{anno: 2019, value: 0}]},
        { desc: "        - da imprese collegate", cod: "E.C32", values: [{anno: 2019, value: 0}]},
        { desc: "        - da imprese controllanti", cod: "E.C33", values: [{anno: 2019, value: 0}]},
        { desc: "        - altri", cod: "E.C35", values: [{anno: 2019, value: 0}]},
        { desc: "    17-bis) Utili e perdite su cambi", cod: "E.C4", values: [{anno: 2019, value: 0}]},
        { desc: "D) Rettifiche di valore di attività finanziarie", cod: "E.D", values: [{anno: 2019, value: 0}]},
        { desc: "    18) Rivalutazioni", cod: "E.D1", values: [{anno: 2019, value: 0}]},
        { desc: "        a) di partecipazioni", cod: "E.D11", values: [{anno: 2019, value: 0}]},
        { desc: "            con il metodo del patrimonio netto", cod: "E.D111", values: [{anno: 2019, value: 0}]},
        { desc: "            altre", cod: "E.D112", values: [{anno: 2019, value: 0}]},
        { desc: "        b) di immobilizzazioni finanziarie", cod: "E.D12", values: [{anno: 2019, value: 0}]},
        { desc: "        c) di titoli inscritti nell'attivo circolante", cod: "E.D13", values: [{anno: 2019, value: 0}]},
        { desc: "    19) Svalutazioni", cod: "E.D2", values: [{anno: 2019, value: 0}]},
        { desc: "        a) di partecipazioni", cod: "E.D21", values: [{anno: 2019, value: 0}]},
        { desc: "            con il metodo del patrimonio netto", cod: "E.D211", values: [{anno: 2019, value: 0}]},
        { desc: "            altre", cod: "E.D212", values: [{anno: 2019, value: 0}]},
        { desc: "        b) di immobilizzazioni finanziarie", cod: "E.D22", values: [{anno: 2019, value: 0}]},
        { desc: "        c) di titoli inscritti nell'attivo circolante", cod: "E.D23", values: [{anno: 2019, value: 0}]},
        { desc: "E) Proventi e oneri straordinari", cod: "E.E", values: [{anno: 2019, value: 0}]},
        { desc: "    20) Proventi straordinari", cod: "E.E1", values: [{anno: 2019, value: 0}]},
        { desc: "        - Plusvalenze non produzione", cod: "E.E11", values: [{anno: 2019, value: 0}]},
        { desc: "        - Varie", cod: "E.E12", values: [{anno: 2019, value: 0}]},
        { desc: "            - Varie", cod: "E.E121", values: [{anno: 2019, value: 0}]},
        { desc: "            - Proventi (Oneri) straordinari per redazione Bilancio in Euro (2 decimali)", cod: "E.E122", values: [{anno: 2019, value: 0}]},
        { desc: "    21) Oneri straordinari", cod: "E.E2", values: [{anno: 2019, value: 0}]},
        { desc: "        - Minusvalenze non produzione", cod: "E.E21", values: [{anno: 2019, value: 0}]},
        { desc: "        - Imposte su esercizi precedenti", cod: "E.E22", values: [{anno: 2019, value: 0}]},
        { desc: "        - Varie", cod: "E.E23", values: [{anno: 2019, value: 0}]},
        { desc: "Risultato prima delle imposte", cod: "E.F", values: [{anno: 2019, value: 0}]},
        { desc: "22) Imposte sul reddito dell'esercizio", cod: "E.F1", values: [{anno: 2019, value: 0}]},
        { desc: "    a) Imposte correnti", cod: "E.F11", values: [{anno: 2019, value: 0}]},
        { desc: "    b) Imposte differite", cod: "E.F12", values: [{anno: 2019, value: 0}]},
        { desc: "    c) Imposte anticipate", cod: "E.F13", values: [{anno: 2019, value: 0}]},
        { desc: "    d) Proventi (oneri) da adesione al regime di consolidato fiscale / trasparenza fiscale", cod: "E.F14", values: [{anno: 2019, value: 0}]},
        { desc: "23) Utile (Perdita) dell'esercizio", cod: "E.F2", values: [{anno: 2019, value: 0}]},
        { desc: "Utile (perdita) dell'esercizio di pertinenza di terzi", cod: "E.G", values: [{anno: 2019, value: 0}]},
        { desc: "Utile (perdita) dell'esercizio di pertinenza per il gruppo", cod: "E.H", values: [{anno: 2019, value: 0}]},
        { desc: "Riclassificazione SP secondo il criterio finanziario", cod: "", values: [{anno: 2019, value: 0}]},
        { desc: "Immobilizzazioni Immateriali", cod: "IMM.1", values: [{anno: 2019, value: 0}]},
        { desc: "Immobilizzazioni materiali", cod: "IMM.2", values: [{anno: 2019, value: 0}]},
        { desc: "Immobilizzazioni finanziarie", cod: "IMM.3", values: [{anno: 2019, value: 0}]},
        { desc: "TOTALE IMMOBILIZZAZIONI", cod: "IMM", values: [{anno: 2019, value: 0}]},
        { desc: "Attività consolidate", cod: "ATTCONS", values: [{anno: 2019, value: 0}]},
        { desc: "Rimanenze", cod: "RIMA", values: [{anno: 2019, value: 0}]},
        { desc: "Clienti", cod: "LD1", values: [{anno: 2019, value: 0}]},
        { desc: "Altri crediti entro 12 mesi", cod: "LD2", values: [{anno: 2019, value: 0}]},
        { desc: "Crediti oltre 12 mesi", cod: "CROLTRE12", values: [{anno: 2019, value: 0}]},
        { desc: "Attività finanziarie non immobilizzate", cod: "ATTFINNONIMM", values: [{anno: 2019, value: 0}]},
        { desc: "Liquidità", cod: "LI", values: [{anno: 2019, value: 0}]},
        { desc: "ratei e Risconti attivi", cod: "RATRISATT", values: [{anno: 2019, value: 0}]},
        { desc: "Attività Correnti", cod: "ATTCORR", values: [{anno: 2019, value: 0}]},
        { desc: "Liquidità + crediti + ratei", cod: "LIQCRERAT", values: [{anno: 2019, value: 0}]},
        { desc: "Attività correnti - liquidità", cod: "ATTCORRLIQ", values: [{anno: 2019, value: 0}]},
        { desc: "Totale impieghi (capitale investito)", cod: "CI", values: [{anno: 2019, value: 0}]},
        { desc: "Patrimonio Netto", cod: "PN", values: [{anno: 2019, value: 0}]},
        { desc: "Fondi", cod: "FON", values: [{anno: 2019, value: 0}]},
        { desc: "TFR", cod: "TFR", values: [{anno: 2019, value: 0}]},
        { desc: "debiti finanziari MLT", cod: "MLT", values: [{anno: 2019, value: 0}]},
        { desc: "Passività consolidate", cod: "PMLT", values: [{anno: 2019, value: 0}]},
        { desc: "Passività consolidate + CN", cod: "PMLT+PN", values: [{anno: 2019, value: 0}]},
        { desc: "debiti finanziari BT", cod: "DEBFINBT", values: [{anno: 2019, value: 0}]},
        { desc: "Fornitori", cod: "FORN", values: [{anno: 2019, value: 0}]},
        { desc: "debiti non finanziari oltre 12 mesi", cod: "DFB", values: [{anno: 2019, value: 0}]},
        { desc: "debiti non finanziari entro 12 mesi", cod: "DEBNONFINENTR12MES", values: [{anno: 2019, value: 0}]},
        { desc: "ratei e risconti", cod: "RATERIS", values: [{anno: 2019, value: 0}]},
        { desc: "Passività correnti", cod: "PR", values: [{anno: 2019, value: 0}]},
        { desc: "Capitale circolante netto", cod: "CAPCIRNET", values: [{anno: 2019, value: 0}]},
        { desc: "Totale fonti (Passività + Netto)", cod: "TOTFON", values: [{anno: 2019, value: 0}]},
        { desc: "variaz. Cred.+mag.", cod: "VARCREDMAG", values: [{anno: 2019, value: 0}]},
        { desc: "variaz.ricavi", cod: "VARRIC", values: [{anno: 2019, value: 0}]},
        { desc: "variaz.att.cotrr.", cod: "VARATTCOTRR", values: [{anno: 2019, value: 0}]}

      ]
    };
  },
  computed: {
    
  },
  methods: {
    addCol() {
      let len = this.headers.length;
      let last_year = parseInt(this.headers[len - 1].text);
      this.headers.push({text: last_year-1,
          align: "left",
          sortable: false})
      for(let r of this.row) {
        r.values.push({anno: last_year-1, value: 0});
      }
    },
    master(anno, cod) {
      switch(cod) {
        case 'PA.A':
          this.startPAA(anno);
          break;
        case 'PA.A1':
          this.startPAA1(anno);
          break;
        case 'PA.A2':
          this.startPAA2(anno);
          break;
      }
    },
    startPAA1(anno) {
      this.calculatePAA(anno);
    },
    startPAA2(anno) {
      this.calculatePAA(anno);
    },
    calculatePAA(anno) {
      let index_anno = 2019 - parseInt(anno);
      this.row[1].values[index_anno].value = this.row[2].values[index_anno].value + this.row[3].values[index_anno].value;
      this.calculatePA(anno);
    },
    calculatePA(anno) {
      let index_anno = 2019 - parseInt(anno);
      this.row[0].values[index_anno].value = this.row[1].values[index_anno].value;
    }
  } 
}
</script>

<style lang="scss" scoped>
</style>

